### ISSUE TITLE
Bot Not Working?

### ISSUE THREAD

**Issue by JennPfeiffer** [yeah568/telegram-emoji-stats#1]
Hi @yeah568,
thanks for your amazing [Telegram](https://telegram.org/) bot. I added the bot to a group chat but it is not replying. Can you help me please? 🤔

**Comment by yeah568** [comment]
Unfortunately the server that was hosting it died quite a while back, but feel free to clone this repo and set up a version for yourself!

**Comment by JennPfeiffer** [comment]
Do you have a VPS where you could revive your bot @yeah568?
